language: ruby
dist: focal

jobs:
  include:
    - stage: ":ship: it"
      addons:
        snaps:
        - name: docker
          channel: latest/beta
        - name: google-cloud-cli
      script: make ship
      if: (branch = master and type = push ) OR commit_message =~ /ship:docker/ OR env(SHIP_DOCKER) = true
